"""empty message

Revision ID: e12263056a94
Revises: 1960b35d3ff0
Create Date: 2022-01-26 15:48:20.613393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e12263056a94'
down_revision = '1960b35d3ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_loging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sys_admin_log')
    op.create_foreign_key(None, 'sys_role_power', 'sys_role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'sys_role_power', 'sys_power', ['power_id'], ['id'])
    op.create_foreign_key(None, 'sys_user_role', 'sys_role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'sys_user_role', 'sys_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sys_user_role', type_='foreignkey')
    op.drop_constraint(None, 'sys_user_role', type_='foreignkey')
    op.drop_constraint(None, 'sys_role_power', type_='foreignkey')
    op.drop_constraint(None, 'sys_role_power', type_='foreignkey')
    op.create_table('sys_admin_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('method', mysql.VARCHAR(collation='utf8mb4_general_ci', length=10), nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('desc', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('ip', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('success', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_agent', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.drop_table('sys_loging')
    # ### end Alembic commands ###
